# FROM node
FROM node:20.9.0-alpine3.18

WORKDIR /frontend

COPY . .

RUN npm i -g pnpm
RUN pnpm i

# CMD npm start or;
CMD ["npm", "start"]
EXPOSE 5173

# --------------------------------
# $ cd /frontend
# $ docker build -t frontend .
# $ docker run -p 5173:5173 --name frontend frontend
# $ docker run -d -p 5173:5173 --name frontend frontend
# $ docker run -d -p 80:5173 --name frontend80 umutplvn/frontend   // bir port numarasi yazmiyorsak default http de 80 dir // https de 443 dur
# Browser: http://localhost:5173