version: "3.9" # optional.

services:

    frontend:
        # container_name: frontend (default: keyName)
        image: docker-compose-frontend
        build: ./frontend
        ports:
            # external/internal port numbers
            - 5173:5173
            - 3000:5173
            - 80:5173
        restart: on-failure # restarts incase of an error
        depends_on:
            # Start the ones in below first.
            - backend # described below.

    backend:
        image: docker-compose-backend
        build: ./backend
        ports:
            - 8000:8000
        restart: on-failure
        volumes:
            # Physical ways (external:internal)
            - $PWD/backend/logs:/backend/logs
            - $PWD/backend/upload:/backend/upload

# --------------------------------
# $ docker compose up # Start compose.
# $ docker compose up -d --build # Open in deamon mode and run again.
# $ docker compose down # Close compose.
# $ docker compose down -v # compose Close all.
        
